### ISSUE TITLE
AttributeError: module 'attr' has no attribute 's'

### ISSUE THREAD

**Issue by allclearsec** [gnebbia/kb#10]
I install all requirements and try this cmd in first, 
then google error and make 
```
$ pip uninstall attr
$ pip install attrs
```
didn't work for me
```
kb list -v
Traceback (most recent call last):
  File "/usr/local/bin/kb", line 11, in <module>
    load_entry_point('kb==0.1.1', 'console_scripts', 'kb')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/kb-0.1.1-py3.8.egg/kb/main.py", line 19, in <module>
    from kb.commands.add import add
  File "/usr/local/lib/python3.8/dist-packages/kb-0.1.1-py3.8.egg/kb/commands/add.py", line 19, in <module>
    import kb.db as db
  File "/usr/local/lib/python3.8/dist-packages/kb-0.1.1-py3.8.egg/kb/db.py", line 21, in <module>
    from kb.entities.artifact import Artifact
  File "/usr/local/lib/python3.8/dist-packages/kb-0.1.1-py3.8.egg/kb/entities/artifact.py", line 18, in <module>
    @attr.s(auto_attribs=True, frozen=True, slots=True)
AttributeError: module 'attr' has no attribute 's'
```

## Specifications

  - Platform: Linux parrot 5.7.0-2parrot2-amd64 #1 SMP Debian 5.7.10-1parrot2 (2020-07-31) x86_64 GNU/Linux

**Comment by gnebbia** [comment]
What version of python are you using?
Try to do:
pip install --upgrade attrs

**Comment by allclearsec** [comment]
> What version of python are you using?
> Try to do:
> pip install --upgrade attrs

Thank you! i use pip3 for this, but this helps
