### ISSUE TITLE
Arch not launching avec update

### ISSUE THREAD

**Issue by sachaz** [gnebbia/kb#106]
Hi,

After un update today with kb (0.1.7-1) and Python 3.11.3, I got:

~~~
$ kb
Traceback (most recent call last):
  File "/usr/bin/kb", line 33, in <module>
    sys.exit(load_entry_point('kb-manager==0.1.7', 'console_scripts', 'kb')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/kb", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sacha/.local/lib/python3.11/site-packages/kb/main.py", line 19, in <module>
    from kb.commands.add import add
  File "/home/sacha/.local/lib/python3.11/site-packages/kb/commands/add.py", line 19, in <module>
    import kb.db as db
  File "/home/sacha/.local/lib/python3.11/site-packages/kb/db.py", line 21, in <module>
    from kb.entities.artifact import Artifact
  File "/home/sacha/.local/lib/python3.11/site-packages/kb/entities/artifact.py", line 18, in <module>
    @attr.s(auto_attribs=True, frozen=True, slots=True)
     ^^^^^^
AttributeError: module 'attr' has no attribute 's'
~~~

**Comment by sachaz** [comment]
solved with:
pip uninstall attr then pip uninstall attrs then pip install attrs
