### ISSUE TITLE
Install not working with pipx, colored.exception.InvalidStyle error

### ISSUE THREAD

**Issue by randomcoder67** [gnebbia/kb#108]
## Expected Behavior

Installs with pipx and works 

## Actual Behavior

Gives an error when trying to launch: 

```
Traceback (most recent call last):
  File "/home/username/.local/bin/kb", line 5, in <module>
    from kb.main import main
  File "/home/username/.local/pipx/venvs/kb-manager/lib/python3.11/site-packages/kb/main.py", line 20, in <module>
    from kb.commands.search import search
  File "/home/username/.local/pipx/venvs/kb-manager/lib/python3.11/site-packages/kb/commands/search.py", line 17, in <module>
    import kb.printer.search as printer
  File "/home/username/.local/pipx/venvs/kb-manager/lib/python3.11/site-packages/kb/printer/search.py", line 15, in <module>
    from kb.printer.style import ALT_BGROUND, BOLD, UND, RESET
  File "/home/username/.local/pipx/venvs/kb-manager/lib/python3.11/site-packages/kb/printer/style.py", line 20, in <module>
    UND = styler.set_style('underlined')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/.local/pipx/venvs/kb-manager/lib/python3.11/site-packages/kb/styler.py", line 58, in set_style
    return colored.attr(style)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/username/.local/pipx/venvs/kb-manager/lib/python3.11/site-packages/colored/colored.py", line 263, in attr
    return Colored(name).attribute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/.local/pipx/venvs/kb-manager/lib/python3.11/site-packages/colored/colored.py", line 64, in attribute
    self._utils.is_style_exist(self._name)
  File "/home/username/.local/pipx/venvs/kb-manager/lib/python3.11/site-packages/colored/utilities.py", line 53, in is_style_exist
    raise InvalidStyle(f'{InvalidStyle.__name__}: {name}')
colored.exceptions.InvalidStyle: InvalidStyle: underlined
```

## Steps to Reproduce the Problem

`pipx install kb-manager`
`kb`

## Specifications

  - Version:`package kb-manager 0.1.7, installed using Python 3.11.3

  - Platform: Arch Latest
  - Subsystem: pipx

**Comment by octoshrimpy** [comment]
Same thing here. Endeavouros (arch), otherwise everything the same.

**Comment by AaronFeldman** [comment]
Same error using ubuntu/wayland python3

**Comment by gnebbia** [comment]
This has been fixed, it was because of a name change in the library "colored"
