### ISSUE TITLE
KeyError: 'underline'

### ISSUE THREAD

**Issue by tykinnison** [gnebbia/kb#110]
I'm no longer able to launch KB after a system update on 2023-August-30.

$ kb
Traceback (most recent call last):
  File "/usr/bin/kb", line 33, in <module>
    sys.exit(load_entry_point('kb-manager==0.1.7', 'console_scripts', 'kb')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/kb", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/kb/main.py", line 20, in <module>
    from kb.commands.search import search
  File "/usr/lib/python3.11/site-packages/kb/commands/search.py", line 17, in <module>
    import kb.printer.search as printer
  File "/usr/lib/python3.11/site-packages/kb/printer/search.py", line 15, in <module>
    from kb.printer.style import ALT_BGROUND, BOLD, UND, RESET
  File "/usr/lib/python3.11/site-packages/kb/printer/style.py", line 20, in <module>
    UND = styler.set_style('underline')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/kb/styler.py", line 58, in set_style
    return colored.attr(style)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gage/.local/lib/python3.11/site-packages/colored/colored.py", line 427, in attr
    return colored(color).attribute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gage/.local/lib/python3.11/site-packages/colored/colored.py", line 323, in attribute
    return paint[self.color]
           ~~~~~^^^^^^^^^^^^
KeyError: 'underline'

Arch btw, and thanks for KB, I love it!

**Comment by sirhc** [comment]
I ran into this as well. Looks like the colored library changed the name of the underline style, while kb still uses underlined.

https://gitlab.com/dslackw/colored/-/blob/master/CHANGES.md#fixed-1

I was able to get it working again by changing the value in my kb installation.

https://github.com/gnebbia/kb/blob/fa365a39f033f3da05e7d174e609285d200f4d3e/kb/printer/style.py#L20

**Comment by gnebbia** [comment]
This has been fixed!

**Comment by jimu** [comment]
> This has been fixed!

The problem is still evident as of 2025-07-23:
```
$ kb --version
kb 0.1.8
$ kb list zip
Traceback (most recent call last):
  File "/usr/local/bin/kb", line 5, in <module>
    from kb.main import main
  File "/usr/local/lib/python3.8/site-packages/kb/main.py", line 20, in <module>
    from kb.commands.search import search
  File "/usr/local/lib/python3.8/site-packages/kb/commands/search.py", line 17, in <module>
    import kb.printer.search as printer
  File "/usr/local/lib/python3.8/site-packages/kb/printer/search.py", line 15, in <module>
    from kb.printer.style import ALT_BGROUND, BOLD, UND, RESET
  File "/usr/local/lib/python3.8/site-packages/kb/printer/style.py", line 20, in <module>
    UND = styler.set_style('underline')
  File "/usr/local/lib/python3.8/site-packages/kb/styler.py", line 58, in set_style
    return colored.attr(style)
  File "/usr/local/lib/python3.8/site-packages/colored/colored.py", line 427, in attr
    return colored(color).attribute()
  File "/usr/local/lib/python3.8/site-packages/colored/colored.py", line 323, in attribute
    return paint[self.color]
KeyError: 'underline'
```

The workaround suggested by sirhc [here](https://github.com/gnebbia/kb/issues/110#issuecomment-1703920827) still works.

**Comment by gnebbia** [comment]
This is strange i just tried on a fresh install and everything worked, with the latest version of the module colored. How did you install kb?

**Comment by jimu** [comment]
> This is strange i just tried on a fresh install and everything worked, with the latest version of the module colored. How did you install kb?

```
# pip3.8 install -U kb-manager
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3.8 install --user` instead.
Requirement already up-to-date: kb-manager in /usr/local/lib/python3.8/site-packages (0.1.8)
Requirement already satisfied, skipping upgrade: toml in /usr/local/lib/python3.8/site-packages (from kb-manager) (0.10.2)
Requirement already satisfied, skipping upgrade: attrs in /usr/local/lib/python3.8/site-packages (from kb-manager) (25.3.0)
Requirement already satisfied, skipping upgrade: gitpython in /usr/local/lib64/python3.8/site-packages (from kb-manager) (3.1.44)
Requirement already satisfied, skipping upgrade: colored in /usr/local/lib/python3.8/site-packages (from kb-manager) (1.4.4)
Requirement already satisfied, skipping upgrade: attr in /usr/local/lib/python3.8/site-packages (from kb-manager) (0.3.2)
Requirement already satisfied, skipping upgrade: gitdb<5,>=4.0.1 in /usr/local/lib/python3.8/site-packages (from gitpython->kb-manager) (4.0.12)
Requirement already satisfied, skipping upgrade: smmap<6,>=3.0.1 in /usr/local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython->kb-manager) (5.0.2)
```
