### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by deep5050** [gnebbia/kb#113]
```bash
deep@Lap-148:/bin$ kb
Traceback (most recent call last):
  File "/home/deep/.local/bin/kb", line 5, in <module>
    from kb.main import main
  File "/home/deep/.local/lib/python3.10/site-packages/kb/main.py", line 20, in <module>
    from kb.commands.search import search
  File "/home/deep/.local/lib/python3.10/site-packages/kb/commands/search.py", line 17, in <module>
    import kb.printer.search as printer
  File "/home/deep/.local/lib/python3.10/site-packages/kb/printer/search.py", line 15, in <module>
    from kb.printer.style import ALT_BGROUND, BOLD, UND, RESET
  File "/home/deep/.local/lib/python3.10/site-packages/kb/printer/style.py", line 20, in <module>
    UND = styler.set_style('underlined')
  File "/home/deep/.local/lib/python3.10/site-packages/kb/styler.py", line 58, in set_style
    return colored.attr(style)
  File "/home/deep/.local/lib/python3.10/site-packages/colored/colored.py", line 263, in attr
    return Colored(name).attribute()
  File "/home/deep/.local/lib/python3.10/site-packages/colored/colored.py", line 64, in attribute
    self._utils.is_style_exist(self._name)
  File "/home/deep/.local/lib/python3.10/site-packages/colored/utilities.py", line 53, in is_style_exist
    raise InvalidStyle(f'{InvalidStyle.__name__}: {name}')
colored.exceptions.InvalidStyle: InvalidStyle: underlined

```

**Comment by pcantalupo** [comment]
I'm getting a the same exception

```
  File "/home/pc/.local/lib/python3.9/site-packages/colored/utilities.py", line 53, in is_style_exist
    raise InvalidStyle(f'{InvalidStyle.__name__}: {name}')
colored.exceptions.InvalidStyle: InvalidStyle: underlined
```

**Comment by james-weigle** [comment]
Same here. Pip seems to be installing an older version of the code: "underlined" was updated to "underline" in [this commit](https://github.com/gnebbia/kb/commit/862a1abc68da7af5128dfb346a2c0f22e2cc9c1d). Unfortunately, [Pip's latest version](https://pypi.org/project/kb-manager/) is from September 21, 2022.

**Comment by james-weigle** [comment]
Update: installing the bleeding-edge version resolved this issue for me:
```pip install -U git+https://github.com/gnebbia/kb```
