### ISSUE TITLE
AttributeError: 'str' object has no attribute 'mkdir'

### ISSUE THREAD

**Issue by KennethMod** [gnebbia/kb#14]
Hi,

I am getting the following error

``
$ kb add test
Traceback (most recent call last):
  File "/usr/local/bin/kb", line 11, in <module>
    load_entry_point('kb==0.1.1', 'console_scripts', 'kb')()
  File "/usr/local/lib/python3.6/site-packages/kb-0.1.1-py3.6.egg/kb/main.py", line 62, in main
    dispatch(cmd, cmd_params, config=DEFAULT_CONFIG)
  File "/usr/local/lib/python3.6/site-packages/kb-0.1.1-py3.6.egg/kb/main.py", line 52, in dispatch
    return COMMANDS[function](*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kb-0.1.1-py3.6.egg/kb/commands/add.py", line 50, in add
    initializer.init(config)
  File "/usr/local/lib/python3.6/site-packages/kb-0.1.1-py3.6.egg/kb/initializer.py", line 37, in init
    create_kb_files(config)
  File "/usr/local/lib/python3.6/site-packages/kb-0.1.1-py3.6.egg/kb/initializer.py", line 63, in create_kb_files
    kb_path.mkdir(parents=True, exist_ok=True)
AttributeError: 'str' object has no attribute 'mkdir'
``

From what I can see in config.py these are indeed strings not "Path" objects

Running on RedHat 7.8 

``
Linux xxx 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 11 19:12:04 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
``

**Comment by gnebbia** [comment]
Thanks for your message, please be sure to update kb!
do:
pip uninstall kb
then pull the last commits "git pull" within the kb directory
then do:
pip install . # there is a dot
Let me know if you still have the problem

**Comment by KennethMod** [comment]
Thanks! that was perfect timing :)

Great tool btw, thanks for the good work!

**Comment by gnebbia** [comment]
Thanks a lot for the appreciation and or your issue!
