### ISSUE TITLE
Exception thrown for `kb view --id 90` when 90 does not exist

### ISSUE THREAD

**Issue by jakerobers** [gnebbia/kb#3]
## Expected Behavior

I'd probably expect nothing to return.

## Actual Behavior

```
Traceback (most recent call last):
  File "/usr/local/bin/kb", line 33, in <module>
    sys.exit(load_entry_point('kb', 'console_scripts', 'kb')())
  File "/Users/jake.robers/Code/kb/kb/main.py", line 62, in main
    dispatch(cmd, cmd_params, config=DEFAULT_CONFIG)
  File "/Users/jake.robers/Code/kb/kb/main.py", line 52, in dispatch
    return COMMANDS[function](*args, **kwargs)
  File "/Users/jake.robers/Code/kb/kb/commands/view.py", line 60, in view
    artifact = db.get_artifact_by_id(conn, artifact_id)
  File "/Users/jake.robers/Code/kb/kb/db.py", line 210, in get_artifact_by_id
    return Artifact(*cur.fetchall().pop())
IndexError: pop from empty list
```

## Steps to Reproduce the Problem

View an archive that does not exist on your system.

1. `kb view --id 90` # 90 does not exist on my machine.

**Comment by gnebbia** [comment]
Thanks! Fixed with commit eff10e2!
