### ISSUE TITLE
Code Page issue on Windows

### ISSUE THREAD

**Issue by indiamcq** [gnebbia/kb#42]
## Expected Behavior
Using: pip install -U kb-manager
or pip install -U git+https://github.com/gnebbia/kb

I expected to have kb installed

## Actual Behavior
There is an error related to the code page:
```
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pip.exe\__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\pip\__init__.py", line 28, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "c:\python27\lib\site-packages\pip\vcs\mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "c:\python27\lib\site-packages\pip\download.py", line 37, in <module>
    from pip.utils.ui import DownloadProgressBar, DownloadProgressSpinner
  File "c:\python27\lib\site-packages\pip\utils\ui.py", line 57, in <module>
    _BaseBar = _select_progress_class(IncrementalBar, Bar)
  File "c:\python27\lib\site-packages\pip\utils\ui.py", line 50, in _select_progress_class
    six.text_type().join(characters).encode(encoding)
LookupError: unknown encoding: cp65001
```

## Steps to Reproduce the Problem

 1. At the Windows command prompt.
   1. Use either: 
  - pip install -U kb-manager 
  - or 
  - pip install -U git+https://github.com/gnebbia/kb
  

## Specifications

  - Version: Unknown - current
  - Platform: Windows 10
  - Subsystem:

**Comment by yihong0618** [comment]
Please use python3.6+

**Comment by gnebbia** [comment]
You are trying to use python2, but this software works with Python 3.
