### ISSUE TITLE
Creating a new KB artifact from scratch fails on Windows 10

### ISSUE THREAD

**Issue by AgataZiegenhagen** [gnebbia/kb#58]
## Expected Behavior

kb add --title "ftp" --category "notes" --tags "protocol;network" 

brings up an editor

## Actual Behavior

C:\Users\Uwe>kb add --title "ftp" --category "notes" --tags "protocol;network"
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\kb.exe\__main__.py", line 7, in <module>
  File "c:\anaconda3\lib\site-packages\kb\main.py", line 64, in main
    dispatch(cmd, cmd_params, config=DEFAULT_CONFIG)
  File "c:\anaconda3\lib\site-packages\kb\main.py", line 54, in dispatch
    return COMMANDS[function](*args, **kwargs)
  File "c:\anaconda3\lib\site-packages\kb\commands\add.py", line 80, in add
    call(shell_cmd)
  File "c:\anaconda3\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden (cannot find the specified file)

## Steps to Reproduce the Problem

  1. kb add --title "ftp" --category "notes" --tags "protocol;network" 

## Specifications

  - Version: 0.1.5
  - Platform: Windows 10
  - Subsystem: Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

**Comment by gnebbia** [comment]
I am sorry Sir, I just tested your same command on Windows 10 and it works, I am not able to reproduce the error.
What editor are you using?

**Comment by UweZiegenhagen** [comment]
Thank you for the quick reply. I have tried with Ultraedit as well as with Notepad++

C:\Users\Uwe>echo %EDITOR%
C:\Notepadpp\notepad++.exe

C:\Users\Uwe>kb add --title "ftp" --category "notes" --tags "protocol;network"
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\kb.exe\__main__.py", line 7, in <module>
  File "c:\anaconda3\lib\site-packages\kb\main.py", line 64, in main
    dispatch(cmd, cmd_params, config=DEFAULT_CONFIG)
  File "c:\anaconda3\lib\site-packages\kb\main.py", line 54, in dispatch
    return COMMANDS[function](*args, **kwargs)
  File "c:\anaconda3\lib\site-packages\kb\commands\add.py", line 80, in add
    call(shell_cmd)
  File "c:\anaconda3\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

**Comment by gnebbia** [comment]
ok my guess is that there may be something wrong with anaconda... could you try to install it in an environment without anaconda?
do you really need anaconda?

**Comment by UweZiegenhagen** [comment]
Sorry I found the error, my missing quotes in the %EDITOR% variable.

**Comment by gnebbia** [comment]
Not a problem Sir!
The important thing is that you were able to solve it! Let me know if there is something wrong!
In addition if you updated from 0.1.4 to 0.1.5 please update the aliases, the new ones rock!
