### ISSUE TITLE
Error when using "kb grep -m something"

### ISSUE THREAD

**Issue by am-technix** [gnebbia/kb#63]
## Expected Behavior
Get the result of the grep with detailed search results

## Actual Behavior
Got an exception : 
Traceback (most recent call last):
  File "/home/antoine/.pyenv/versions/3.7.5/bin/kb", line 11, in <module>
    load_entry_point('kb-manager==0.1.5', 'console_scripts', 'kb')()
  File "/home/antoine/.pyenv/versions/3.7.5/lib/python3.7/site-packages/kb_manager-0.1.5-py3.7.egg/kb/main.py", line 64, in main
    dispatch(cmd, cmd_params, config=DEFAULT_CONFIG)
  File "/home/antoine/.pyenv/versions/3.7.5/lib/python3.7/site-packages/kb_manager-0.1.5-py3.7.egg/kb/main.py", line 54, in dispatch
    return COMMANDS[function](*args, **kwargs)
  File "/home/antoine/.pyenv/versions/3.7.5/lib/python3.7/site-packages/kb_manager-0.1.5-py3.7.egg/kb/commands/grep.py", line 66, in grep
    printer.print_grep_matches(artifact_names)
TypeError: print_grep_matches() missing 1 required positional argument: 'hits_list'

## Steps to Reproduce the Problem

  1. Simply use the command, I think...

## Specifications

  - Version: 0.1.5
  - Platform: Linux
  - Subsystem: Ubuntu 20.04

**Comment by gnebbia** [comment]
Sorry Sir, We left the placeholder for future version, the "-m" feature is not still implemented unluckily!
Let's keep this open until we release the feature in the next minor release.
Thanks for using kb!

**Comment by gnebbia** [comment]
Dear Sir, the feature has been implemented as of kb v0.1.6! So I am going to close this issue!
