### ISSUE TITLE
Module 'attr' has no attribute 's'

### ISSUE THREAD

**Issue by hapidznur** [gnebbia/kb#66]
## Expected Behavior
Working Normally

## Actual Behavior
```shell
 $ kb
Traceback (most recent call last):
  File "/usr/local/bin/kb", line 11, in <module>
    load_entry_point('kb-manager==0.1.5', 'console_scripts', 'kb')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/site-packages/kb_manager-0.1.5-py3.8.egg/kb/main.py", line 19, in <module>
    from kb.commands.add import add
  File "/usr/local/lib/python3.8/site-packages/kb_manager-0.1.5-py3.8.egg/kb/commands/add.py", line 20, in <module>
    import kb.db as db
  File "/usr/local/lib/python3.8/site-packages/kb_manager-0.1.5-py3.8.egg/kb/db.py", line 21, in <module>
    from kb.entities.artifact import Artifact
  File "/usr/local/lib/python3.8/site-packages/kb_manager-0.1.5-py3.8.egg/kb/entities/artifact.py", line 17, in <module>
    @attr.s(auto_attribs=True, frozen=True, slots=True)
AttributeError: module 'attr' has no attribute 's'
```

## Steps to Reproduce the Problem

  1. Install kb from pip
  2. Run kb

## Specifications

  - Version: Python 3.8.6, kb 0.1.5
  - Platform: Fedora 32 SilverBlue

Have same issue? I already install both of attr and attrs package. But not solving issue.

**Comment by gnebbia** [comment]
Try to force an upgrade on those packages by doing:
pip install -U attr
pip istall -U attrs

Let me know.

**Comment by hapidznur** [comment]
Solved. Need uninstall attr and attes. Install kb then install attr and attrs again. Thanks.
