### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 10: invalid continuation byte

### ISSUE THREAD

**Issue by hodgins96** [gnebbia/kb#8]
## Expected Behavior
trying to open pdf

## Actual Behavior
Traceback (most recent call last):
  File "/usr/local/bin/kb", line 33, in <module>
    sys.exit(load_entry_point('kb==0.1.1', 'console_scripts', 'kb')())
  File "/usr/local/lib/python3.8/site-packages/kb-0.1.1-py3.8.egg/kb/main.py", line 62, in main
    dispatch(cmd, cmd_params, config=DEFAULT_CONFIG)
  File "/usr/local/lib/python3.8/site-packages/kb-0.1.1-py3.8.egg/kb/main.py", line 52, in dispatch
    return COMMANDS[function](*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/kb-0.1.1-py3.8.egg/kb/commands/view.py", line 78, in view
    viewer.view(artifact_path, markers, color=color_mode)
  File "/usr/local/lib/python3.8/site-packages/kb-0.1.1-py3.8.egg/kb/viewer.py", line 115, in view
    content = fname.read()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 10: invalid continuation byte

## Steps to Reproduce the Problem

  1.kb add /Users/spencer/Code/pass/throwaway.pdf --title throwAway-Quote --category Project --tags "throwaway"
  1.kbv 0
  1.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 10: invalid continuation byte

## Specifications

  - Version: kb 0.1.0
  - Platform: Mac OS 
  - Subsystem:

**Comment by gnebbia** [comment]
Dear Sir, unluckily at the moment kb opens files based on their title extension (this may change in the next release anyway),
so be sure to add the file with --title throwAway-Quote.pdf.

**Comment by hodgins96** [comment]
Thanks for the Swift response
